repos:
  - repo: local
    hooks:
      - id: validate-expense-rulebook
        name: Validate expense_rulebook.json
        entry: ./ruler_poc/ruler_server/validate_rulebook.py --schema ruler_poc/ruler_server/expense_rulebook.schema.json --rulebook ruler_poc/ruler_server/expense_rulebook.json
        language: system
        files: ^expense_rulebook\.json$
        pass_filenames: false
